site_name: 'Example Documentation'
repo_url: https://github.com/marcoolivo-msft/vscode-course-sample
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - Subpage: SECURITY.md
  - Extensions: ext.md

plugins:
  - techdocs-core
